name: ria_green_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Dependências para funcionalidades novas
  flutter_svg: ^2.0.7
  flutter_native_timezone: ^2.0.0
  http: ^1.3.0
  google_sign_in: ^7.2.0
  flutter_secure_storage: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/logo.svg
    - assets/svg/logo2.svg
    - assets/svg/logo3.svg
    - assets/svg/google.svg
    - assets/svg/facebook.svg
    - assets/svg/riapoints.svg
    - assets/svg/recycle.svg
    - assets/svg/location.svg
    - assets/svg/colecao.svg
    - assets/svg/dashboard.svg
    - assets/svg/artigos.svg
    - assets/svg/sejaparceiro.svg
    - assets/svg/outros.svg
    - assets/svg/faq.svg
    - assets/svg/recycleCenter.svg
    - assets/svg/vetorFundo.svg
    - assets/svg/vetorUsuario.svg
    - assets/svg/vetorNavBar.svg
    - assets/svg/home.svg
    - assets/svg/perfil.svg
    - assets/svg/guia.svg
    - assets/images/dia.png
    - assets/images/tarde.png
    - assets/images/noite.png
    - assets/images/Reciclagem-Eletronica.jpg
    - assets/images/Reciclagem-Especializada.jpg
    - assets/images/Pontos-Inteligentes.jpg
    - assets/images/Movimento-Verde.jpg
    - assets/images/Movimento-Verde-Blur.jpg
    - assets/images/avatar.png
    - assets/images/faq_image.png
    - assets/images/guide_image.png


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf